name: v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  http: ^1.2.2
  mobile_scanner: ^5.1.1
  path_provider: ^2.1.4
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
